### ISSUE TITLE
RRSIG support

### ISSUE THREAD

**Issue by moparisthebest** [fardog/secureoperator#13]
Running `dig @127.0.0.1 -p 8853 rrsig debian.org` pointed to dingo gives this log:

```
$ ./secure-operator_linux-amd64 -listen 127.0.0.1:8853 -udp
INFO[0000] starting udp service on 127.0.0.1:8853       
INFO[0000] starting tcp service on 127.0.0.1:8853       
INFO[0004] requesting debian.org. RRSIG                 
ERRO[0006] Error writing DNS response: dns: nil rr
```

And does not return any data, check what should be returned by running `dig @8.8.8.8 rrsig debian.org`

dingo has the same bug [here](https://github.com/pforemski/dingo/issues/39)

https://github.com/chenhw2/google-https-dns seems to work for RRSIG

**Comment by fardog** [comment]
i was able to reproduce this; i'll look into it, see if I can figure why it's failing. thanks!

**Comment by fardog** [comment]
oh interesting; https://github.com/chenhw2/google-https-dns is a kinda-fork of secureoperator. maybe that'll make whatever they've done to fix easy to port in.
